spring:
  cloud:
    alicloud:
      access-key: LTAI4GJqnjN9brgspxziy5NV
      secret-key: 4C2zr7vS13s1vpwj78vtDXw8OEwuLn
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hellozd
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000